# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.building.build_main import Analysis, PYZ, EXE, COLLECT
import os
from PyInstaller.lib.core.setup import get_toc # Import get_toc to work with TOCs

block_cipher = None

# --------------------------
# Data folders (copy intact)
# --------------------------
# The source path is relative to the spec file.
# The destination path is relative to the bundle's internal structure.
# We'll keep the destination path relative to the internal structure here
# and fix the final location in the COLLECT step.
datas = [
    ('config', 'config'),  # src: 'config' folder, dest: 'config' folder in bundle
    ('data', 'data')       # src: 'data' folder, dest: 'data' folder in bundle
]

# --------------------------
# Analysis
# --------------------------
a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    cipher=block_cipher,
    noarchive=False
)

# --------------------------
# Build PYZ and EXE (No changes needed here)
# --------------------------
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    exclude_binaries=True,
    name='teamgen',
    debug=False,
    strip=False,
    upx=True,
    console=True
)

# --------------------------
# Collect into dist/teamgen/
# --------------------------
# 1. Manually create a TOC from the Analysis datas.
# 2. Modify the TOC to set the destination to an empty string ('')
#    which forces the files to the root of the COLLECT folder.

# Get the list of data files generated by Analysis
data_files = a.datas

# Re-package the data files with an empty destination path
# This tells COLLECT to put them at the top level.
external_data_files = [
    (src, '', dest_type) for src, dest, dest_type in data_files
]

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    # Use the manually adjusted data list instead of a.datas
    *external_data_files,
    strip=False,
    upx=True,
    name='teamgen'
)


